const ADMIN_PIN = "1415"; 

const client = supabase.createClient(
  'https://aoekbmhgbohsgpwqsizv.supabase.co', 
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZWtibWhnYm9oc2dwd3FzaXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDU1OTEsImV4cCI6MjEwMjUyMTU5MX0.ikCySPlyg0kPHt0sx34pndAWJAJ9tVCyWonBuG-lLQU'
);

const tableConfigs = {
  plan: { label: '📅 Месечен План', table: 'plan', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Детайл', type: 'text', readonly: true }, { name: 'Вътрешно име', type: 'text', required: true }, { name: 'Целево количество', type: 'number', required: true }, { name: 'Месец', type: 'text', required: true }, { name: 'Година', type: 'number', required: true }, { name: 'Статус', type: 'select', options: ['Активен', 'Завършен', '📦 Опакован', '🚚 Изпратен'], required: true } ] },
  personal: { label: '👥 Персонал & Досиета', table: 'personal', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'Имейл', type: 'text', required: true }, { name: 'Име', type: 'text' }, { name: 'Статус', type: 'select', options: ['Активен', 'Блокиран'], required: true, def: 'Активен' } ] },
  chekiraniya: { label: '⏱️ Хронология Чекирания', table: 'chekiraniya', readOnlyTab: true, fields: [ { name: 'Време', type: 'text' }, { name: 'Имейл', type: 'text' }, { name: 'Действие', type: 'text' }, { name: 'Локация', type: 'text' }, { name: 'Бележка', type: 'text' } ] },
  sklad_gp: { label: '🏭 Склад Готови Детайли', table: 'inventory_gp', readOnlyTab: true, fields: [ { name: 'ID Детайл', type: 'text', readonlyOnEdit: true }, { name: 'Име', type: 'text', readonlyOnEdit: true }, { name: 'Локация', type: 'text', readonlyOnEdit: true }, { name: 'Операция', type: 'text', readonlyOnEdit: true }, { name: 'Общо', type: 'number', readonlyOnEdit: true }, { name: 'Запазени', type: 'text', readonlyOnEdit: true }, { name: 'Свободни', type: 'number', readonlyOnEdit: true }, { name: 'Минимално количество/Буфер', type: 'number', def: 0 }, { name: '% Брак', type: 'number', def: 0 } ] },
  sklad_wip: { label: '⏳ Склад Полуфабрикати', table: 'inventory_wip', readOnlyTab: true, fields: [ { name: 'ID Детайл', type: 'text', readonlyOnEdit: true }, { name: 'Име', type: 'text', readonlyOnEdit: true }, { name: 'Локация', type: 'text', readonlyOnEdit: true }, { name: 'Операция', type: 'text', readonlyOnEdit: true }, { name: 'Общо', type: 'number', readonlyOnEdit: true }, { name: 'Запазени', type: 'text', readonlyOnEdit: true }, { name: 'Свободни', type: 'number', readonlyOnEdit: true }, { name: 'Минимално количество/Буфер', type: 'number', def: 0 } ] },
  nomenklatura: { label: '🗂️ Номенклатура', table: 'Номенклатура', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Детайл', type: 'text', required: true }, { name: 'Вътрешно име', type: 'text' }, { name: 'Тип', type: 'text' }, { name: 'ID Родител', type: 'text' }, { name: 'Разходна норма', type: 'number', def: 1 }, { name: 'Единици', type: 'text', def: 'бр.' }, { name: 'Линк към чертеж', type: 'text' } ] },
  sklad: { label: '📦 Склад Материали', table: 'sklad', key: 'ID Детайл', fields: [ { name: 'ID Детайл', type: 'text', required: true, readonlyOnEdit: true }, { name: 'Мерна единица', type: 'text' }, { name: 'Начална наличност', type: 'number', def: 0 }, { name: 'Доставено', type: 'number', def: 0 }, { name: 'Изразходено', type: 'number', def: 0 }, { name: 'Остатък', type: 'number', def: 0, readonly: true }, { name: 'Минимално количество', type: 'number', def: 0 }, { name: 'Бележки', type: 'text' } ] },
  bom: { label: '🧩 БОМ (Разбивка)', table: 'bom', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Родител', type: 'text', required: true }, { name: 'ID Компонент', type: 'text', required: true }, { name: 'Количество', type: 'number', required: true, def: 1 }, { name: 'Влага се на Оп. №', type: 'number' } ] },
  marshruti: { label: '🔄 Маршрутни карти', table: 'marshruti', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'Код на детайла', type: 'text', required: true }, { name: '№ Операция', type: 'number', required: true, def: 10 }, { name: 'Име на операция', type: 'text', required: true }, { name: 'Машина', type: 'text' }, { name: 'Описание', type: 'text' }, { name: 'Инструкция за оставяне', type: 'text' }, { name: 'Линк към чертеж', type: 'text' }, { name: 'Линк към СОП', type: 'text' } ] },
  otcheti: { label: '📊 Отчети (Log)', table: 'otcheti', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID План', type: 'text' }, { name: 'ID Детайл', type: 'text', required: true }, { name: 'Операция', type: 'text', required: true }, { name: 'Количество', type: 'number', def: 1, required: true }, { name: 'Статус', type: 'select', options: ['Отчетено', 'Брак', 'Изпратено'], required: true }, { name: 'Оператор', type: 'text', required: true }, { name: 'Дата', type: 'text', def: () => new Date().toISOString() } ] },
  porachki: { label: '🛒 Поръчки материали', table: 'porachki_materiali', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'Материал', type: 'text', required: true }, { name: 'Дата на поръчка', type: 'date', def: () => new Date().toISOString().split('T')[0] }, { name: 'Доставчик', type: 'text' }, { name: 'Имейл на доставчик', type: 'text' }, { name: 'Количество', type: 'number', required: true, def: 1 }, { name: 'Дата на приемане', type: 'date' }, { name: 'Статус', type: 'select', options: ['Поръчано', 'Прието'], required: true, def: 'Поръчано' } ] }
};

let currentTab = 'plan'; 
let globalRows = []; 
let currentRenderedRows = []; 
let selectedIndices = new Set();
let isEditMode = false; 
let editingIndex = null; 
let currentFolderEmail = '';

