const ADMIN_PIN = "1415"; 

const client = supabase.createClient(
  'https://aoekbmhgbohsgpwqsizv.supabase.co', 
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZWtibWhnYm9oc2dwd3FzaXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDU1OTEsImV4cCI6MjEwMjUyMTU5MX0.ikCySPlyg0kPHt0sx34pndAWJAJ9tVCyWonBuG-lLQU'
);

const tableConfigs = {
  plan: { label: 'рџ“… РњРµСЃРµС‡РµРЅ РџР»Р°РЅ', table: 'plan', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', readonly: true }, { name: 'Р’СЉС‚СЂРµС€РЅРѕ РёРјРµ', type: 'text', required: true }, { name: 'Р¦РµР»РµРІРѕ РєРѕР»РёС‡РµСЃС‚РІРѕ', type: 'number', required: true }, { name: 'РњРµСЃРµС†', type: 'text', required: true }, { name: 'Р“РѕРґРёРЅР°', type: 'number', required: true }, { name: 'РЎС‚Р°С‚СѓСЃ', type: 'select', options: ['РђРєС‚РёРІРµРЅ', 'Р—Р°РІСЉСЂС€РµРЅ', 'рџ“¦ РћРїР°РєРѕРІР°РЅ', 'рџљљ РР·РїСЂР°С‚РµРЅ'], required: true } ] },
  personal: { label: 'рџ‘Ґ РџРµСЂСЃРѕРЅР°Р» & Р”РѕСЃРёРµС‚Р°', table: 'personal', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'РРјРµР№Р»', type: 'text', required: true }, { name: 'РРјРµ', type: 'text' }, { name: 'РЎС‚Р°С‚СѓСЃ', type: 'select', options: ['РђРєС‚РёРІРµРЅ', 'Р‘Р»РѕРєРёСЂР°РЅ'], required: true, def: 'РђРєС‚РёРІРµРЅ' } ] },
  chekiraniya: { label: 'вЏ±пёЏ РҐСЂРѕРЅРѕР»РѕРіРёСЏ Р§РµРєРёСЂР°РЅРёСЏ', table: 'chekiraniya', readOnlyTab: true, fields: [ { name: 'Р’СЂРµРјРµ', type: 'text' }, { name: 'РРјРµР№Р»', type: 'text' }, { name: 'Р”РµР№СЃС‚РІРёРµ', type: 'text' }, { name: 'Р›РѕРєР°С†РёСЏ', type: 'text' }, { name: 'Р‘РµР»РµР¶РєР°', type: 'text' } ] },
  sklad_gp: { label: 'рџЏ­ РЎРєР»Р°Рґ Р“РѕС‚РѕРІРё Р”РµС‚Р°Р№Р»Рё', table: 'inventory_gp', readOnlyTab: true, fields: [ { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', readonlyOnEdit: true }, { name: 'РРјРµ', type: 'text', readonlyOnEdit: true }, { name: 'Р›РѕРєР°С†РёСЏ', type: 'text', readonlyOnEdit: true }, { name: 'РћРїРµСЂР°С†РёСЏ', type: 'text', readonlyOnEdit: true }, { name: 'РћР±С‰Рѕ', type: 'number', readonlyOnEdit: true }, { name: 'Р—Р°РїР°Р·РµРЅРё', type: 'text', readonlyOnEdit: true }, { name: 'РЎРІРѕР±РѕРґРЅРё', type: 'number', readonlyOnEdit: true }, { name: 'РњРёРЅРёРјР°Р»РЅРѕ РєРѕР»РёС‡РµСЃС‚РІРѕ/Р‘СѓС„РµСЂ', type: 'number', def: 0 }, { name: '% Р‘СЂР°Рє', type: 'number', def: 0 } ] },
  sklad_wip: { label: 'вЏі РЎРєР»Р°Рґ РџРѕР»СѓС„Р°Р±СЂРёРєР°С‚Рё', table: 'inventory_wip', readOnlyTab: true, fields: [ { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', readonlyOnEdit: true }, { name: 'РРјРµ', type: 'text', readonlyOnEdit: true }, { name: 'Р›РѕРєР°С†РёСЏ', type: 'text', readonlyOnEdit: true }, { name: 'РћРїРµСЂР°С†РёСЏ', type: 'text', readonlyOnEdit: true }, { name: 'РћР±С‰Рѕ', type: 'number', readonlyOnEdit: true }, { name: 'Р—Р°РїР°Р·РµРЅРё', type: 'text', readonlyOnEdit: true }, { name: 'РЎРІРѕР±РѕРґРЅРё', type: 'number', readonlyOnEdit: true }, { name: 'РњРёРЅРёРјР°Р»РЅРѕ РєРѕР»РёС‡РµСЃС‚РІРѕ/Р‘СѓС„РµСЂ', type: 'number', def: 0 } ] },
  nomenklatura: { label: 'рџ—‚пёЏ РќРѕРјРµРЅРєР»Р°С‚СѓСЂР°', table: 'РќРѕРјРµРЅРєР»Р°С‚СѓСЂР°', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', required: true }, { name: 'Р’СЉС‚СЂРµС€РЅРѕ РёРјРµ', type: 'text' }, { name: 'РўРёРї', type: 'text' }, { name: 'ID Р РѕРґРёС‚РµР»', type: 'text' }, { name: 'Р Р°Р·С…РѕРґРЅР° РЅРѕСЂРјР°', type: 'number', def: 1 }, { name: 'Р•РґРёРЅРёС†Рё', type: 'text', def: 'Р±СЂ.' }, { name: 'Р›РёРЅРє РєСЉРј С‡РµСЂС‚РµР¶', type: 'text' } ] },
  sklad: { label: 'рџ“¦ РЎРєР»Р°Рґ РњР°С‚РµСЂРёР°Р»Рё', table: 'sklad', key: 'ID Р”РµС‚Р°Р№Р»', fields: [ { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', required: true, readonlyOnEdit: true }, { name: 'РњРµСЂРЅР° РµРґРёРЅРёС†Р°', type: 'text' }, { name: 'РќР°С‡Р°Р»РЅР° РЅР°Р»РёС‡РЅРѕСЃС‚', type: 'number', def: 0 }, { name: 'Р”РѕСЃС‚Р°РІРµРЅРѕ', type: 'number', def: 0 }, { name: 'РР·СЂР°Р·С…РѕРґРµРЅРѕ', type: 'number', def: 0 }, { name: 'РћСЃС‚Р°С‚СЉРє', type: 'number', def: 0, readonly: true }, { name: 'РњРёРЅРёРјР°Р»РЅРѕ РєРѕР»РёС‡РµСЃС‚РІРѕ', type: 'number', def: 0 }, { name: 'Р‘РµР»РµР¶РєРё', type: 'text' } ] },
  bom: { label: 'рџ§© Р‘РћРњ (Р Р°Р·Р±РёРІРєР°)', table: 'bom', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID Р РѕРґРёС‚РµР»', type: 'text', required: true }, { name: 'ID РљРѕРјРїРѕРЅРµРЅС‚', type: 'text', required: true }, { name: 'РљРѕР»РёС‡РµСЃС‚РІРѕ', type: 'number', required: true, def: 1 }, { name: 'Р’Р»Р°РіР° СЃРµ РЅР° РћРї. в„–', type: 'number' } ] },
  marshruti: { label: 'рџ”„ РњР°СЂС€СЂСѓС‚РЅРё РєР°СЂС‚Рё', table: 'marshruti', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'РљРѕРґ РЅР° РґРµС‚Р°Р№Р»Р°', type: 'text', required: true }, { name: 'в„– РћРїРµСЂР°С†РёСЏ', type: 'number', required: true, def: 10 }, { name: 'РРјРµ РЅР° РѕРїРµСЂР°С†РёСЏ', type: 'text', required: true }, { name: 'РњР°С€РёРЅР°', type: 'text' }, { name: 'РћРїРёСЃР°РЅРёРµ', type: 'text' }, { name: 'РРЅСЃС‚СЂСѓРєС†РёСЏ Р·Р° РѕСЃС‚Р°РІСЏРЅРµ', type: 'text' }, { name: 'Р›РёРЅРє РєСЉРј С‡РµСЂС‚РµР¶', type: 'text' }, { name: 'Р›РёРЅРє РєСЉРј РЎРћРџ', type: 'text' } ] },
  otcheti: { label: 'рџ“Љ РћС‚С‡РµС‚Рё (Log)', table: 'otcheti', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'ID РџР»Р°РЅ', type: 'text' }, { name: 'ID Р”РµС‚Р°Р№Р»', type: 'text', required: true }, { name: 'РћРїРµСЂР°С†РёСЏ', type: 'text', required: true }, { name: 'РљРѕР»РёС‡РµСЃС‚РІРѕ', type: 'number', def: 1, required: true }, { name: 'РЎС‚Р°С‚СѓСЃ', type: 'select', options: ['РћС‚С‡РµС‚РµРЅРѕ', 'Р‘СЂР°Рє', 'РР·РїСЂР°С‚РµРЅРѕ'], required: true }, { name: 'РћРїРµСЂР°С‚РѕСЂ', type: 'text', required: true }, { name: 'Р”Р°С‚Р°', type: 'text', def: () => new Date().toISOString() } ] },
  porachki: { label: 'рџ›’ РџРѕСЂСЉС‡РєРё РјР°С‚РµСЂРёР°Р»Рё', table: 'porachki_materiali', key: 'id', fields: [ { name: 'id', type: 'number', readonly: true, hideOnAdd: true }, { name: 'РњР°С‚РµСЂРёР°Р»', type: 'text', required: true }, { name: 'Р”Р°С‚Р° РЅР° РїРѕСЂСЉС‡РєР°', type: 'date', def: () => new Date().toISOString().split('T')[0] }, { name: 'Р”РѕСЃС‚Р°РІС‡РёРє', type: 'text' }, { name: 'РРјРµР№Р» РЅР° РґРѕСЃС‚Р°РІС‡РёРє', type: 'text' }, { name: 'РљРѕР»РёС‡РµСЃС‚РІРѕ', type: 'number', required: true, def: 1 }, { name: 'Р”Р°С‚Р° РЅР° РїСЂРёРµРјР°РЅРµ', type: 'date' }, { name: 'РЎС‚Р°С‚СѓСЃ', type: 'select', options: ['РџРѕСЂСЉС‡Р°РЅРѕ', 'РџСЂРёРµС‚Рѕ'], required: true, def: 'РџРѕСЂСЉС‡Р°РЅРѕ' } ] }
};

let currentTab = 'plan'; 
let globalRows = []; 
let currentRenderedRows = []; 
let selectedIndices = new Set();
let isEditMode = false; 
let editingIndex = null; 
let currentFolderEmail = '';



